version: '3'

services:
  auth:
    build: ./auth
    ports:
      - "${AUTH_PORT}:50051"
    depends_on:
      - postgres
      - redis-auth
    networks:
      - microservice-network

  chat-server:
    build: ./chat-server
    ports:
      - "${CHAT_PORT}:50052"
    depends_on:
      - postgres
      - redis-chat
    networks:
      - microservice-network

  postgres:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${POSTGRES_DB:-postgres}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservice-network

  redis-auth:
    image: redis:7.2-alpine
    ports:
      - "${AUTH_REDIS_PORT}:6379"
    volumes:
      - redisauth:/data
    networks:
      - microservice-network

  redis-chat:
    image: redis:7.2-alpine
    ports:
      - "${CHAT_REDIS_PORT}:6379"
    volumes:
      - redischat:/data
    networks:
      - microservice-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: postgres
    networks:
      - microservice-network

volumes:
  pgdata:
  redisauth:
  redischat:

networks:
  microservice-network:
    driver: bridge
